### ISSUE TITLE
Error running colab notebook: load_weights() fails

### ISSUE THREAD

**Issue by twilwa** [xjdr-alt/entropix#10]
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
[<ipython-input-6-d0ff32815be4>](https://localhost:8080/#) in <cell line: 76>()
     74     return xfmr_weights
     75 
---> 76 xfmr_weights = load_weights()

[<ipython-input-6-d0ff32815be4>](https://localhost:8080/#) in load_weights(ckpt_dir, n_layers, debug)
     54         for i in range(n_layers):
     55             layer_weights.append(LayerWeights(
---> 56                 wq=w[f'layers.{i}.attention.wq.weight'],
     57                 wk=w[f'layers.{i}.attention.wk.weight'],
     58                 wv=w[f'layers.{i}.attention.wv.weight'],

KeyError: 'layers.0.attention.wq.weight'
```

I presume I've probably got a setting or something set wrong, but it seems to me like the notebook isn't loading the weights or downloading the model (or if it is, it's doing so unusually quickly, and I'm not seeing it in the file explorer, only folder is 'sample_data'). I also don't see any output when running the cells; despite selecting show/hide output a few times on each. Adding print statements seems to work okay though, and I double-checked for TPU runtime/tested with a GPU runtime (number of devices error as expected.) Curious if there were some initial instructions I missed or a common error/setting to check.

**Comment by xjdr-alt** [comment]
you need to make sure you add your token and the top of the file and then uncomment the download_weights() method in order to get the weights into your colab

**Comment by gillandsiphon** [comment]
When I last tried the colab, I had to 1) uncomment download_weights() and 2) add my huggingface token since the model is gated.
