### ISSUE TITLE
Question regarding KV cache

### ISSUE THREAD

**Issue by AakashKumarNain** [xjdr-alt/entropix#14]
Before I send a PR, just wanted to ask if the current KV cache implementation combines prefill and decoding in the same code?

**Comment by xjdr-alt** [comment]
yes, it does. More sophisticated caching will be added soon to separate them so we can do the proper parallel CoT decoding.

**Comment by AakashKumarNain** [comment]
Thanks. I think the current implementation can be simplified, but I will wait
