### ISSUE TITLE
Repository pytorch does not exist error related to package install of torch using poetry

### ISSUE THREAD

**Issue by SinatrasC** [xjdr-alt/entropix#43]
As user trys to run `poetry lock && poetry install` using latest pyproject.totml a error stating pytorch repository does not exist will prevent user installing the full package even though its marked as optional. Will pr the fix i applied on my case.

![resim](https://github.com/user-attachments/assets/91071029-b7b6-400c-8765-f8d73841e56f)

**Comment by JushBJJ** [comment]
I found a solution for this, opening a PR soon

**Comment by SinatrasC** [comment]
> I found a solution for this, opening a PR soon

Already fixed with PR #44

**Comment by JushBJJ** [comment]
Your fix is removing pytorch lol
